import type { Metadata } from "next";
import { League_Spartan } from "next/font/google";
import "./globals.css";
import GlobalContextProvider from "./Context";


const LSpartan = League_Spartan({
  subsets: ["latin"],
  weight: ["700", "600", "500"],
});

export const metadata: Metadata = {
  title: "invoice-app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={LSpartan.className}>
        <GlobalContextProvider>
          {children}
        </GlobalContextProvider>
      </body>
    </html>
  );
}
